In [1]:
print('Hello World!')

Hello World!


# NumPy
---
### Basic of Numpy

In [60]:
import numpy as np
arr  = np.array([1,2,3])
print(f'{arr.ndim} Dimensional array.')
print(arr)
arr2 = np.array(
    [[1.0 , 2.0 , 3.0],
    [4.0 , 5.0 , 6.5]
    ])
print(f'{arr2.ndim} Dimensionals array.')
print(arr2)
arr3 = np.array([
    [1.0 , 2.0 , 3.0],
    [4.0 , 5.0 , 6.5],
    [7.7 , 8.0 , 9.5]
])
print(f'{arr3.ndim} Dimensionals array.')
print(arr3)
d3_arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(f'{d3_arr.ndim} Dimensionals array.')
print(d3_arr)

1 Dimensional array.
[1 2 3]
2 Dimensionals array.
[[1.  2.  3. ]
 [4.  5.  6.5]]
2 Dimensionals array.
[[1.  2.  3. ]
 [4.  5.  6.5]
 [7.7 8.  9.5]]
3 Dimensionals array.
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
# Get Dimension
print(arr.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
2


In [17]:
# Get Shape
print(arr.shape)
print(arr2.shape)
print(arr3.shape)

(3,)
(2, 3)
(3, 3)


In [18]:
# Get Type
print(arr.dtype)
print(arr2.dtype)
print(arr3.dtype)

int64
float64
float64


In [24]:
arr4 = np.array([1,2,3],dtype='int32')
print(arr4.dtype)

int32


In [26]:
# Get Size
print(arr.itemsize)
print(arr2.itemsize)
print(arr3.itemsize)
print(arr4.itemsize)

8
8
8
4


In [31]:
# Get Totalsize
print(arr.size * arr.itemsize)
print(arr.nbytes)

24
24


### Accessing/Changing specific elements, rows colums,etc

In [32]:
arr2_7 = np.array([[0 ,1,2,3,4,5,6],[7,8,9,10,11,12,13]])
print(arr2_7.shape)

(2, 7)


In [36]:
# Get the specific elements [row,colum]
print(arr2_7[0,6])
print(arr2_7[1,6])
print(arr2_7[1,-1])

6
13
13


In [37]:
# Get a specific row
print(arr2_7[0,:])
print(arr2_7[0,1:3])

[0 1 2 3 4 5 6]
[1 2]


In [47]:
# Get a specific colum
print(arr2_7[:,1])
print(arr2_7[:1,1])
print(arr2_7[:2,1])
print(arr2_7[1:2,1])

[1 8]
[1]
[1 8]
[8]


In [50]:
arr2_7[1,6] = 31 # row 1 colum 6 element 13 to replace with 31
print('row 1 colum 6 element 13 to replace with 31')
print(arr2_7)

row 1 colum 6 element 13 to replace with 31
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 31]]


In [53]:
# changing the multiple elements 
arr2_7[:,0] = 9
arr2_7[0,:] = 9
print(arr2_7)

[[ 9  9  9  9  9  9  9]
 [ 9  8  9 10 11 12 31]]


* 3-d example

In [58]:
d3_arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d3_arr.shape)
print(d3_arr)

(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [59]:
# Get the specific elements 
# Getting the shape  0, row 1, colum 1 (4) 
print(d3_arr[0,1,1])

4


In [61]:
# replacing the element in 3D array
d3_arr[0,1,1] = 44
print(d3_arr)

[[[ 1  2]
  [ 3 44]]

 [[ 5  6]
  [ 7  8]]]


In [62]:
# replacing with multiple 
# replacing all Shape ,row 1 , all colum 
d3_arr[:,1,:] = [9,9],[8,8]
print(d3_arr)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### Initializing Different Types of Arrays

In [67]:
# All 0s matrix
one = np.zeros(4)
print(one)


[0. 0. 0. 0.]


In [68]:
two = np.zeros((2,4))
print(two)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [69]:
three = np.zeros((2,3,4))
print(three)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [70]:
# All 1s matrix
allOne = np.ones((3,3,3))
print(allOne)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [83]:
# Any othe number 
anyNum = np.full((3,3,3),99)
print(anyNum)

[[[99 99 99]
  [99 99 99]
  [99 99 99]]

 [[99 99 99]
  [99 99 99]
  [99 99 99]]

 [[99 99 99]
  [99 99 99]
  [99 99 99]]]


In [84]:
# Any other number (full_like)
anyNum_full_like = np.full_like(anyNum,5)
print(anyNum_full_like)

[[[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]]


In [85]:
# Random decimal number
random_matrix = np.random.rand(4,3)
print(random_matrix)

[[0.22732047 0.97263183 0.29683658]
 [0.58013653 0.45945941 0.01575487]
 [0.96258092 0.99995274 0.10559418]
 [0.85251098 0.10728508 0.53926574]]


In [82]:
# Random integer values
import numpy as np
random_matrix_array = np.random.randint(1,10,size=(3,3,4))
print(random_matrix_array)

[[[9 8 5 8]
  [6 9 2 5]
  [7 7 4 7]]

 [[1 3 4 1]
  [1 2 1 6]
  [5 3 8 7]]

 [[9 8 5 3]
  [2 7 2 3]
  [5 6 2 6]]]


In [86]:
# The identity matrix
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [91]:
# Repeat an array
arr = np.array([[1,2,3]])
repeat_arr = np.repeat(arr,3,axis=0)
print(repeat_arr)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [95]:
# Repeat an array
arr = np.array([[[1,2,3]]])
repeat_arr = np.repeat(arr,3,axis=0)
print(repeat_arr)

[[[1 2 3]]

 [[1 2 3]]

 [[1 2 3]]]


In [100]:
output = np.ones((5,5))
print(output)
zero = np.zeros((3,3))
print(zero)
zero[1,1] = 9
print(zero)
output[1:4,1:4] = zero
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [102]:
output = np.ones((5,5),dtype="int32")
zero = np.zeros((3,3))
zero[1,1] = 9
output[1:4,1:4] = zero
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Be careful when copying arrays!

In [109]:
orignal = np.array([1,2,3,4,5])
print(orignal)
assing_arr = orignal
assing_arr[0] = 100 # changing the element of assing_arr 
print('assing_arr',assing_arr)
print('orignal array aslo change',orignal)
real_copy = orignal.copy()
real_copy[0] = 1 # changing the element of real_copy
print('real_copy',real_copy)
print('orignal array does\'t change',orignal)

[1 2 3 4 5]
assing_arr [100   2   3   4   5]
orignal array aslo change [100   2   3   4   5]
real_copy [1 2 3 4 5]
orignal array does't change [100   2   3   4   5]


## Mathematics
---

In [110]:
arr = np.array([1,2,3,4])

In [111]:
print(arr+2)

[3 4 5 6]


In [112]:
print(arr-2)

[-1  0  1  2]


In [113]:
print(arr*2)

[2 4 6 8]


In [114]:
print(arr/2)

[0.5 1.  1.5 2. ]


In [115]:
print(arr**2)

[ 1  4  9 16]


In [119]:
# Take the sin/cose ..
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [120]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Liniar Algebra

In [125]:
a = np.ones((2,3))
print(a)
print()
b = np.full((3,2),2)
print(b)
print()
ab = np.matmul(a,b)
print(ab)

[[1. 1. 1.]
 [1. 1. 1.]]

[[2 2]
 [2 2]
 [2 2]]

[[6. 6.]
 [6. 6.]]


In [126]:
# find the determinant
c = np.identity(3)
detC=np.linalg.det(c)
print(detC)

1.0


In [127]:
print(dir(np.linalg))

['LinAlgError', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_umath_linalg', 'cholesky', 'cond', 'det', 'eig', 'eigh', 'eigvals', 'eigvalsh', 'inv', 'linalg', 'lstsq', 'matrix_power', 'matrix_rank', 'multi_dot', 'norm', 'pinv', 'qr', 'slogdet', 'solve', 'svd', 'tensorinv', 'tensorsolve', 'test']


### Statistics

In [142]:
stats = np.array([[1,2,3],[4,5,6]])
print(np.min(stats,axis = 1))
print(np.max(stats))
print(np.max(stats,axis=1))
print(np.sum(stats))
print(np.sum(stats, axis= 0))
print(np.sum(stats, axis= 1))
print(np.sum(stats, axis= (0,1)))
print(np.sum(stats, axis= -1))

[1 4]
6
[3 6]
21
[5 7 9]
[ 6 15]
21
[ 6 15]


In [137]:
print(help(np.sum))

Help on function sum in module numpy:

sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Sum of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In 